slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping #localization 

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    # map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true

    # debug_logging: false # Change logger to debug
    # throttle_scans: 1 # Number of scans to throttle in synchronous mode
    # transform_publish_period: 0.005 # The map to odom transform publish period. 0 will not publish transforms
    map_update_interval: 2.0 # Interval to update the 2D occupancy map for other applications / visualization
    resolution: 0.05 # Resolution of the 2D occupancy map to generate
    # max_laser_range: 20.0 # Maximum laser range to use for 2D occupancy map rastering / SPAZIO BLU RVIZ IN CUI CARICA LA MAPPA
    # minimum_time_interval: 0.5 # The minimum duration of time between scans to be processed in synchronous mode
    # transform_timeout: 0.2 # TF timeout for looking up transforms
    # tf_buffer_duration: 30. # Duration to store TF messages for lookup. Set high if running offline at multiple times speed in synchronous mode.
    # stack_size_to_use: 40000000 # The number of bytes to reset the stack size to, to enable serialization/deserialization of files. A liberal default is 40000000, but less is fine.
    # enable_interactive_mode: true # Whether or not to allow for interactive mode to be enabled. Interactive mode will retain a cache of laser scans mapped to their ID for visualization in interactive mode. As a result the memory for the process will increase. This is manually disabled in localization and lifelong modes since they would increase the memory utilization over time. Valid for either mapping or continued mapping modes.

    # # General Parameters
    # use_scan_matching: true # whether to use scan matching to refine odometric pose 
    # use_scan_barycenter: true # Whether to use the barycenter or scan pose
    # minimum_travel_distance: 0.2 # Minimum distance of travel before processing a new scan
    # minimum_travel_heading: 0.2 # Minimum changing in heading to justify an update
    # scan_buffer_size: 10 # The number of scans to buffer into a chain, also used as the number of scans in the circular buffer of localization mode
    # scan_buffer_maximum_scan_distance: 10.0 # Maximum distance of a scan from the pose before removing the scan from the buffer
    # link_match_minimum_response_fine: 0.1 # The threshold link matching algorithm response for fine resolution to pass
    # link_scan_maximum_distance: 1.5 # Maximum distance between linked scans to be valid
    # loop_search_maximum_distance: 3.0 # Maximum threshold of distance for scans to be considered for loop closure
    # do_loop_closing: true # Whether to do loop closure
    # loop_match_minimum_chain_size: 10 # The minimum chain length of scans to look for loop closure          
    # loop_match_maximum_variance_coarse: 3.0 # The threshold variance in coarse search to pass to refine
    # loop_match_minimum_response_coarse: 0.35 # The threshold response of the loop closure algorithm in coarse search to pass to refine
    # loop_match_minimum_response_fine: 0.45 # The threshold response of the loop closure algorithm in fine search to pass to refine

    # # Correlation Parameters - Correlation Parameters
    # correlation_search_space_dimension: 0.5 # Search grid size to do scan correlation over
    # correlation_search_space_resolution: 0.01 # Search grid resolution to do scan correlation over
    # correlation_search_space_smear_deviation: 0.1 # Amount of multimodal smearing to smooth out responses

    # # Correlation Parameters - Loop Closure Parameters
    # loop_search_space_dimension: 8.0 # Size of the search grid over the loop closure algorith
    # loop_search_space_resolution: 0.05 # Search grid resolution to do loop closure over
    # loop_search_space_smear_deviation: 0.03 # Amount of multimodal smearing to smooth out responses

    # # Scan Matcher Parameters
    # distance_variance_penalty: 0.5 # A penalty to apply to a matched scan as it differs from the odometric pose
    # angle_variance_penalty: 1.0 # A penalty to apply to a matched scan as it differs from the odometric pose

    # fine_search_angle_offset: 0.00349 # Range of angles to test for fine scan matching
    # coarse_search_angle_offset: 0.349 # ange of angles to test for coarse scan matching
    # coarse_angle_resolution: 0.0349 # Resolution of angles over the Offset range to test in scan matching
    # minimum_angle_penalty: 0.9 # Smallest penalty an angle can have to ensure the size doesn't blow up
    # minimum_distance_penalty: 0.5 # Smallest penalty a scan can have to ensure the size doesn't blow up
    # use_response_expansion: true # Whether to automatically increase the search grid size if no viable match is found